Updating setup

diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -31,7 +31,7 @@ read -p "Enter the password you want to use for root postgresql user: " POSTGRES
 echo "Installing dependencies"
 if [[ $PLATFORM == 'Linux' ]]; then
   sudo apt-get update
-  sudo apt-get -qqy install coreutils autoconf libtool curl git-core ruby bison build-essential zlib1g-dev libssl-dev libreadline5-dev
+  sudo apt-get -qqy install coreutils autoconf libtool curl git-core ruby bison build-essential zlib1g-dev libssl-dev libreadline5
 else
   echo "Sorry, we can't install dependencies for your system yet."
 fi
@@ -60,8 +60,13 @@ if [ -f ~/.bashrc ]; then
 fi
 
 echo "Installing rvm"
-curl -s -k -B https://rvm.beginrescueend.com/install/rvm > /tmp/install_rvm
-bash /tmp/install_rvm
+#curl -s -k -B https://rvm.beginrescueend.com/install/rvm > /tmp/install_rvm
+bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer) > /tmp/install_rvm
+if [ "$?" != "0" ]; then
+    echo "failed to install rvm, cancelling setup"
+    exit 1
+fi
+#bash /tmp/install_rvm
 rm /tmp/install_rvm
 
 echo "Activate rvm"
